package com.example.test3.AddIngredients

data class IngredientItem(
    val name: String,
    val category: String
)

val groceryIngredientList = listOf(
    // Vegetables
    IngredientItem("Tomato", "Vegetables"),
    IngredientItem("Cucumber", "Vegetables"),
    IngredientItem("Carrot", "Vegetables"),
    IngredientItem("Broccoli", "Vegetables"),
    IngredientItem("Spinach", "Vegetables"),
    IngredientItem("Kale", "Vegetables"),
    IngredientItem("Lettuce", "Vegetables"),
    IngredientItem("Bell Pepper", "Vegetables"),
    IngredientItem("Onion", "Vegetables"),
    IngredientItem("Garlic", "Vegetables"),
    IngredientItem("Potato", "Vegetables"),
    IngredientItem("Sweet Potato", "Vegetables"),
    IngredientItem("Zucchini", "Vegetables"),
    IngredientItem("Celery", "Vegetables"),
    IngredientItem("Green Beans", "Vegetables"),
    IngredientItem("Mushroom", "Vegetables"),
    IngredientItem("Asparagus", "Vegetables"),
    IngredientItem("Cabbage", "Vegetables"),
    IngredientItem("Cauliflower", "Vegetables"),
    IngredientItem("Radish", "Vegetables"),

    // Fruits
    IngredientItem("Apple", "Fruits"),
    IngredientItem("Banana", "Fruits"),
    IngredientItem("Orange", "Fruits"),
    IngredientItem("Grapes", "Fruits"),
    IngredientItem("Strawberries", "Fruits"),
    IngredientItem("Blueberries", "Fruits"),
    IngredientItem("Watermelon", "Fruits"),
    IngredientItem("Pineapple", "Fruits"),
    IngredientItem("Avocado", "Fruits"),
    IngredientItem("Mango", "Fruits"),
    IngredientItem("Lemon", "Fruits"),
    IngredientItem("Peach", "Fruits"),
    IngredientItem("Pear", "Fruits"),
    IngredientItem("Kiwi", "Fruits"),
    IngredientItem("Plum", "Fruits"),

    // Proteins
    IngredientItem("Chicken Breast", "Proteins"),
    IngredientItem("Chicken Wing", "Proteins"),
    IngredientItem("Chicken Drumstick", "Proteins"),
    IngredientItem("Ground Beef", "Proteins"),
    IngredientItem("Pork Chops", "Proteins"),
    IngredientItem("Bacon", "Proteins"),
    IngredientItem("Sausage", "Proteins"),
    IngredientItem("Salmon", "Proteins"),
    IngredientItem("Shrimp", "Proteins"),
    IngredientItem("Tuna", "Proteins"),
    IngredientItem("Turkey", "Proteins"),
    IngredientItem("Ham", "Proteins"),
    IngredientItem("Eggs", "Proteins"),
    IngredientItem("Tofu", "Proteins"),
    IngredientItem("Tempeh", "Proteins"),
    IngredientItem("Black Beans", "Proteins"),
    IngredientItem("Chickpeas", "Proteins"),

    // Dairy
    IngredientItem("Milk", "Dairy"),
    IngredientItem("Butter", "Dairy"),
    IngredientItem("Yogurt", "Dairy"),
    IngredientItem("Cheese", "Dairy"),
    IngredientItem("Cheddar Cheese", "Dairy"),
    IngredientItem("Mozzarella", "Dairy"),
    IngredientItem("Parmesan", "Dairy"),
    IngredientItem("Cottage Cheese", "Dairy"),
    IngredientItem("Sour Cream", "Dairy"),
    IngredientItem("Cream Cheese", "Dairy"),
    IngredientItem("Almond Milk", "Dairy"),
    IngredientItem("Oat Milk", "Dairy"),
    IngredientItem("Heavy Cream", "Dairy"),
    IngredientItem("Greek Yogurt", "Dairy"),

    // Grains
    IngredientItem("Rice", "Grains"),
    IngredientItem("Pasta", "Grains"),
    IngredientItem("Spaghetti", "Grains"),
    IngredientItem("Macaroni", "Grains"),
    IngredientItem("Bread", "Grains"),
    IngredientItem("Tortillas", "Grains"),
    IngredientItem("Bagels", "Grains"),
    IngredientItem("Cereal", "Grains"),
    IngredientItem("Oats", "Grains"),
    IngredientItem("Granola", "Grains"),
    IngredientItem("Instant Oatmeal", "Grains"),
    IngredientItem("Crackers", "Grains"),
    IngredientItem("Couscous", "Grains"),
    IngredientItem("Quinoa", "Grains"),
    IngredientItem("Brown Rice", "Grains"),

    //Pantry
    IngredientItem("Lentils", "Pantry"),
    IngredientItem("Canned Beans", "Pantry"),
    IngredientItem("Canned Corn", "Pantry"),
    IngredientItem("Tomato Sauce", "Pantry"),
    IngredientItem("Olive Oil", "Pantry"),
    IngredientItem("Vegetable Oil", "Pantry"),
    IngredientItem("Flour", "Pantry"),
    IngredientItem("Sugar", "Pantry"),
    IngredientItem("Brown Sugar", "Pantry"),
    IngredientItem("Salt", "Pantry"),
    IngredientItem("Pepper", "Pantry"),
    IngredientItem("Honey", "Pantry"),
    IngredientItem("Peanut Butter", "Pantry"),
    IngredientItem("Jam", "Pantry"),
    IngredientItem("Maple Syrup", "Pantry"),
    IngredientItem("Soy Sauce", "Pantry"),
    IngredientItem("Vinegar", "Pantry"),
    IngredientItem("Hot Sauce", "Pantry"),
    IngredientItem("Baking Powder", "Pantry"),
    IngredientItem("Baking Soda", "Pantry"),
    IngredientItem("Corn Starch", "Pantry"),
    IngredientItem("Yeast", "Pantry"),

    // Snacks
    IngredientItem("Chips", "Snacks"),
    IngredientItem("Pretzels", "Snacks"),
    IngredientItem("Popcorn", "Snacks"),
    IngredientItem("Nuts", "Snacks"),
    IngredientItem("Trail Mix", "Snacks"),
    IngredientItem("Chocolate", "Snacks"),
    IngredientItem("Cookies", "Snacks"),
    IngredientItem("Granola Bars", "Snacks"),
    IngredientItem("Fruit Snacks", "Snacks")
)
